ALTER TABLE novels ADD COLUMN IF NOT EXISTS prevent_copy BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE novels ADD COLUMN IF NOT EXISTS prevent_screenshot BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chapters ADD COLUMN IF NOT EXISTS prevent_copy BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE chapters ADD COLUMN IF NOT EXISTS prevent_screenshot BOOLEAN NOT NULL DEFAULT FALSE;

