import {useEffect,useMemo,useState} from "react";
import {api} from "../utils/api";
type Kind='reader'|'writer'; type Action='grant'|'activate'|'deactivate'|'revoke'|'extend'|'shorten'|'renew'|'pause'|'resume'|'expire'|'set_dates'|'make_permanent'|'make_temporary';
const durations=[['3 روز',3],['1 ماه',30],['2 ماه',60],['3 ماه',90],['6 ماه',180],['1 سال',365],['روز دلخواه',0]] as const;
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('fa-IR'):'ندارد';
function remaining(row:any){if(!row)return'ندارد';if(row.is_permanent)return'دائمی';const ms=new Date(row.expires_at).getTime()-Date.now();if(ms<=0)return'منقضی‌شده';const days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000);return`${days} روز و ${hours} ساعت`;}
export default function PremiumManagementCards({userId,onChanged}:{userId:string;onChanged?:()=>void|Promise<void>}){
 const[model,setModel]=useState<any>(null),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[durationDays,setDurationDays]=useState(30),[customDays,setCustomDays]=useState(1),[grantType,setGrantType]=useState<'reader'|'writer'|'both'>('reader'),[mode,setMode]=useState<'add'|'replace'|'from_now'|'after_existing'>('add'),[startsAt,setStartsAt]=useState(''),[expiresAt,setExpiresAt]=useState(''),[error,setError]=useState(''),[sameTerms,setSameTerms]=useState(true),[permanent,setPermanent]=useState(false),[combined,setCombined]=useState({readerPermanent:false,writerPermanent:false,readerStarts:'',writerStarts:'',readerExpires:'',writerExpires:'',readerDays:30,writerDays:30});
 const source='admin_grant';
 const selectedDays=durationDays||customDays;
 const seconds=selectedDays*86400;
 const load=async()=>{const token=api.getToken();const r=await fetch(`/api/admin/users/${encodeURIComponent(userId)}/premium`,{headers:token?{'X-CSRF-Token':token}:{},credentials:'same-origin'});setModel(r.ok?await r.json():null)};
 useEffect(()=>{void load()},[userId]);
  const summary=useMemo(()=>model?.effective?.reader&&model?.effective?.writer?'پریمیوم خواننده + نویسنده':model?.effective?.reader?'پریمیوم خواننده':model?.effective?.writer?'پریمیوم نویسنده':'بدون پریمیوم',[model]);
  const confirmAction=(kind:Kind,action:Action,row:any,extra:any)=>{if(action==='revoke')return`پریمیوم ${kind==='reader'?'خواننده':'نویسنده'} لغو خواهد شد. پریمیوم ${kind==='reader'?'نویسنده':'خواننده'} بدون تغییر باقی می‌ماند.`;if(action==='expire')return`پریمیوم ${kind==='reader'?'خواننده':'نویسنده'} بلافاصله منقضی می‌شود. پریمیوم ${kind==='reader'?'نویسنده':'خواننده'} بدون تغییر باقی می‌ماند.`;if(action==='shorten'||(extra.expiresAt&&row?.expires_at&&new Date(extra.expiresAt)<new Date(row.expires_at)))return`مدت دسترسی پریمیوم ${kind==='reader'?'خواننده':'نویسنده'} کوتاه می‌شود. دسترسی دیگر بدون تغییر باقی می‌ماند.`;if(row?.is_permanent&&action==='make_temporary')return`پریمیوم دائمی ${kind==='reader'?'خواننده':'نویسنده'} موقت می‌شود. ادامه می‌دهید؟`;return''};
 const act=async(kind:Kind,action:Action,id?:string,extra:any={})=>{const row=(model?.entitlements||[]).find((x:any)=>x.id===id),warning=confirmAction(kind,action,row,extra);if(warning&&!window.confirm(warning))return;setBusy(true);setError('');const token=api.getToken();const r=await fetch(`/api/admin/users/${encodeURIComponent(userId)}/premium/actions`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-CSRF-Token':token}:{})},credentials:'same-origin',body:JSON.stringify({premiumType:kind,action,entitlementId:id,reason:note,source,...extra})});if(!r.ok)setError((await r.json().catch(()=>({}))).error||'عملیات ناموفق بود');await load();if(r.ok)await onChanged?.();setBusy(false)};
 const grantBoth=async()=>{setBusy(true);const token=api.getToken(),terms={source,reason:note,durationSeconds:permanent||expiresAt?undefined:seconds,permanent,startsAt:startsAt||undefined,expiresAt:permanent?undefined:expiresAt||undefined};const r=await fetch(`/api/admin/users/${encodeURIComponent(userId)}/premium/grant-both`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-CSRF-Token':token}:{})},credentials:'same-origin',body:JSON.stringify(sameTerms?{sameTerms:terms}:{reader:{...terms,permanent:combined.readerPermanent,startsAt:combined.readerStarts||undefined,expiresAt:combined.readerPermanent?undefined:combined.readerExpires||undefined,durationSeconds:combined.readerPermanent||combined.readerExpires?undefined:combined.readerDays*86400},writer:{...terms,permanent:combined.writerPermanent,startsAt:combined.writerStarts||undefined,expiresAt:combined.writerPermanent?undefined:combined.writerExpires||undefined,durationSeconds:combined.writerPermanent||combined.writerExpires?undefined:combined.writerDays*86400}})});if(!r.ok)setError((await r.json()).error);await load();if(r.ok)await onChanged?.();setBusy(false)};
 const grantSelected=()=>grantType==='both'?grantBoth():act(grantType,'grant',undefined,{durationSeconds:permanent||expiresAt?undefined:seconds,permanent,startsAt:startsAt||undefined,expiresAt:permanent?undefined:expiresAt||undefined});
  if(!model)return<div className="text-xs text-slate-500">در حال بارگذاری سوابق پریمیوم…</div>;
 return <div className="space-y-4 rounded-xl border border-slate-700 p-3">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><strong>مدیریت پریمیوم</strong><span className="ml-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-[10px] text-amber-300">{summary}</span></div><div className="flex gap-2"><select aria-label="نوع دسترسی پریمیومی" value={grantType} onChange={e=>setGrantType(e.target.value as typeof grantType)} className="admin-premium-input"><option value="reader">پریمیوم خواننده</option><option value="writer">پریمیوم نویسنده</option><option value="both">خواننده + نویسنده</option></select><button type="button" disabled={busy||!note.trim()} onClick={()=>void grantSelected()} className="rounded bg-violet-600 px-3 py-1 text-xs font-bold text-white disabled:opacity-40">{busy?'در حال ذخیره…':'اعطای مورد انتخاب‌شده'}</button></div></div>
  <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] text-slate-400">مدت پریمیوم<select aria-label="دوره پریمیوم" value={durationDays} onChange={e=>setDurationDays(Number(e.target.value))} className="admin-premium-input mt-1 block w-full">{durations.map(([l,v])=><option key={l} value={v}>{l}</option>)}</select></label>{durationDays===0&&<label className="text-[10px] text-slate-400">تعداد روز<input aria-label="روزهای دلخواه پریمیوم" type="number" min="1" step="1" value={customDays} onChange={e=>setCustomDays(Math.max(1,Number(e.target.value)||1))} className="admin-premium-input mt-1 block w-full" placeholder="تعداد روز را وارد کنید"/></label>}<label className="text-[10px] text-slate-400">تاریخ شروع (اختیاری)<input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="admin-premium-input mt-1 block w-full" title="برای شروع فوری، خالی بگذارید"/></label><input value={note} onChange={e=>setNote(e.target.value)} required placeholder="دلیل داخلی (الزامی)" className="admin-premium-input"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={permanent} onChange={e=>setPermanent(e.target.checked)}/> دسترسی دائمی</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={sameTerms} onChange={e=>setSameTerms(e.target.checked)}/> شرایط یکسان برای هر دو</label></div>
  <p className="text-[10px] text-slate-500">برای شروع فوری پریمیوم، تاریخ شروع را خالی بگذارید. مدت انتخاب‌شده از تاریخ شروع محاسبه می‌شود.</p>
  {grantType==='both'&&!sameTerms&&<div className="grid gap-3 sm:grid-cols-2 rounded-lg border border-slate-700 p-3">{(['reader','writer'] as const).map(kind=><fieldset key={kind} className="space-y-2"><legend className="text-xs font-bold capitalize">{kind==='reader'?'شرایط خواننده':'شرایط نویسنده'}</legend><label className="flex gap-2 text-xs"><input type="checkbox" checked={combined[`${kind}Permanent`]} onChange={e=>setCombined(v=>({...v,[`${kind}Permanent`]:e.target.checked}))}/>دائمی</label><label className="text-[10px]">مدت (روز)<input disabled={combined[`${kind}Permanent`]||!!combined[`${kind}Expires`]} type="number" min="1" className="admin-premium-input block w-full" value={combined[`${kind}Days`]} onChange={e=>setCombined(v=>({...v,[`${kind}Days`]:Number(e.target.value)}))}/></label><label className="text-[10px]">شروع<input type="datetime-local" className="admin-premium-input block w-full" value={combined[`${kind}Starts`]} onChange={e=>setCombined(v=>({...v,[`${kind}Starts`]:e.target.value}))}/></label><label className="text-[10px]">انقضا<input disabled={combined[`${kind}Permanent`]} type="datetime-local" className="admin-premium-input block w-full" value={combined[`${kind}Expires`]} onChange={e=>setCombined(v=>({...v,[`${kind}Expires`]:e.target.value}))}/></label></fieldset>)}</div>}
<div className="grid gap-3 xl:grid-cols-2">{(['reader','writer']as Kind[]).map(kind=>{const rows=(model.entitlements||[]).filter((x:any)=>x.premium_type===kind),effective=rows.find((x:any)=>x.status==='active'&&!x.is_paused&&!x.revoked_at&&(x.is_permanent||new Date(x.expires_at)>new Date())),row=effective||rows[0],payment=(model.payments||[]).find((x:any)=>x.premium_type===kind);return <section key={kind} className="rounded-xl border border-slate-700 bg-slate-950/60 p-3"><div className="flex justify-between"><strong>پریمیوم {kind==='reader'?'خواننده':'نویسنده'}</strong><span className="text-[10px]">مؤثر: {effective?'فعال':'غیرفعال'} · سیستمی: {row?.status||'none'}</span></div><dl className="mt-2 grid grid-cols-2 gap-x-2 text-[10px] text-slate-400"><dt>دسترسی</dt><dd>{row?.is_permanent?'دائمی':row?'موقت':'غیرفعال'}</dd><dt>شروع</dt><dd>{fmt(row?.starts_at)}</dd><dt>انقضا</dt><dd>{row?.is_permanent?'بدون انقضا':fmt(row?.expires_at)}</dd><dt>باقی‌مانده</dt><dd>{remaining(row)}</dd><dt>متوقف‌شده</dt><dd>{row?.is_paused?'بله':'خیر'}</dd><dt>منبع</dt><dd>{row?.source||'ندارد'}</dd><dt>تمدید خودکار / پرداخت</dt><dd>{row?.auto_renew?'روشن':'خاموش'} / {payment?.status||'none'}</dd><dt>آخرین به‌روزرسانی</dt><dd>{fmt(row?.updated_at)}</dd></dl><div className="mt-3 flex flex-wrap gap-1">{!row?<button disabled={busy||!note} onClick={()=>void act(kind,'grant',undefined,{durationSeconds:permanent||expiresAt?undefined:seconds,permanent,startsAt:startsAt||undefined,expiresAt:permanent?undefined:expiresAt||undefined})}>اعطا</button>:<><button disabled={busy||!note} onClick={()=>void act(kind,'activate',row.id,{startsAt:startsAt||new Date().toISOString()})}>فعال‌سازی</button><button disabled={busy||!note} onClick={()=>void act(kind,'deactivate',row.id)}>غیرفعال‌سازی</button><button disabled={busy||!note} onClick={()=>void act(kind,'renew',row.id,{durationSeconds:seconds,extensionMode:mode})}>تمدید</button><button disabled={busy||!note||row.is_permanent} onClick={()=>void act(kind,'extend',row.id,{durationSeconds:seconds,extensionMode:mode})}>افزایش مدت</button><button disabled={busy||!note||row.is_permanent||!expiresAt} onClick={()=>void act(kind,'shorten',row.id,{expiresAt})}>کاهش مدت</button><button disabled={busy||!note||!expiresAt} onClick={()=>void act(kind,'set_dates',row.id,{startsAt:startsAt||undefined,expiresAt})}>تنظیم تاریخ‌ها</button><button disabled={busy||!note||row.is_permanent} onClick={()=>void act(kind,'make_permanent',row.id)}>تبدیل به دائمی</button><button disabled={busy||!note||!row.is_permanent||!expiresAt} onClick={()=>void act(kind,'make_temporary',row.id,{expiresAt})}>تبدیل به موقت</button><button disabled={busy||!note} onClick={()=>void act(kind,row.is_paused?'resume':'pause',row.id)}>{row.is_paused?'ادامه':'توقف موقت'}</button><button disabled={busy||!note} onClick={()=>void act(kind,'expire',row.id)}>انقضای فوری</button><button disabled={busy||!note} onClick={()=>void act(kind,'revoke',row.id)}>لغو</button></>}</div></section>})}</div>
  {error&&<p className="text-xs text-rose-400">{error}</p>}<details className="text-[10px] text-slate-500"><summary>تاریخچه حسابرسی تغییرناپذیر ({model.audit?.length||0})</summary><div className="max-h-48 overflow-auto">{(model.audit||[]).map((x:any)=><div key={x.id}>{fmt(x.occurred_at)} · {x.premium_type} · {x.action_type} · {x.internal_reason||'بدون دلیل'} · {x.correlation_id}</div>)}</div></details><style>{`.admin-premium-input{border:1px solid #334155;border-radius:.4rem;background:#0f172a;padding:.4rem;font-size:.7rem}section button{border-radius:.3rem;background:#334155;padding:.25rem .45rem;font-size:.65rem}section button:disabled{opacity:.35}`}</style>
 </div>
}
