import {db} from'../server/postgres';import{getEffectiveEntitlements}from'../server/utils/premiumEntitlements';import{cache}from'../server/utils/cache';import{publicWorldbuildingCacheKey}from'../server/utils/worldbuilding';
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5174',stamp=Date.now(),password='Wb2!ProductionTest',authorName=`wb_author_${stamp}`,readerName=`wb_reader_${stamp}`,adminName=`wb_admin_${stamp}`,novelId=`wb-novel-${stamp}`;
class Client{cookies=new Map<string,string>();csrf='';async call(method:string,path:string,body?:any){const headers:any={};if(body!==undefined)headers['Content-Type']='application/json';if(this.cookies.size)headers.Cookie=[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; ');if(this.csrf){headers['X-CSRF-Token']=this.csrf;headers.Authorization=`Bearer ${this.csrf}`}const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});for(const raw of (r.headers as any).getSetCookie?.()||[]){const [pair]=raw.split(';'),i=pair.indexOf('=');this.cookies.set(pair.slice(0,i),pair.slice(i+1))}this.csrf=r.headers.get('x-csrf-token')||decodeURIComponent(this.cookies.get('XSRF-TOKEN')||this.csrf);const data=await r.json().catch(()=>({}));return{status:r.status,ok:r.ok,data}}}
const author=new Client(),reader=new Client(),admin=new Client(),created:string[]=[];function check(ok:any,message:string,detail?:any){if(!ok)throw new Error(`${message}: ${JSON.stringify(detail)}`);console.log(`PASS ${message}`)}
try{
 let r=await author.call('POST','/api/auth/register',{username:authorName,email:`${authorName}@example.com`,nickname:'Worldbuilder',password});check(r.ok,'register author',r.data);const authorId=r.data.user.id;
 r=await reader.call('POST','/api/auth/register',{username:readerName,email:`${readerName}@example.com`,nickname:'Reader',password});check(r.ok,'register reader',r.data);const readerId=r.data.user.id;
 r=await admin.call('POST','/api/auth/register',{username:adminName,email:`${adminName}@example.com`,nickname:'Premium Admin',password});check(r.ok,'register premium admin',r.data);const adminId=r.data.user.id;await db.query(`UPDATE users SET role='owner' WHERE id=$1`,[adminId]);
 const premiumAction=async(userId:string,premiumType:'reader'|'writer',action:string,extra:any={})=>admin.call('POST',`/api/admin/users/${userId}/premium/actions`,{premiumType,action,source:'admin_grant',reason:`E2E ${action} ${premiumType}`,...extra});
 r=await premiumAction(readerId,'reader','grant',{durationSeconds:86400});check(r.ok,'admin grants Reader Premium only',r.data);r=await reader.call('GET','/api/auth/me');check(r.ok&&r.data.user.has_reader_premium===true&&r.data.user.is_premium===true&&r.data.user.has_writer_premium===false,'Reader Premium removes ads projection without Writer access',r.data);
 r=await author.call('POST','/api/novels',{id:novelId,title:`Worldbuilding E2E ${stamp}`,author:authorName,coverUrl:'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400',description:'Worldbuilding end-to-end test novel.',genre:'Fantasy',mainCategories:['Fantasy'],subCategories:[],warnings:[],tags:['worldbuilding'],ageRating:'PG-13',chapters:[]});check(r.ok,'create novel',r.data);
 await db.query(`UPDATE novels SET approval_status='approved' WHERE id=$1`,[novelId]);
 r=await premiumAction(authorId,'writer','grant',{durationSeconds:86400});check(r.ok,'admin grants Writer Premium independently',r.data);const writerGrant=r.data.entitlement;check((await getEffectiveEntitlements(authorId,true)).writer,'grant Writer Premium');
 const create=async(resourceType:string,name:string,data:any={},parentId?:string)=>{const x=await author.call('POST',`/api/worldbuilding/${novelId}/resources`,{resourceType,name,subtype:'Other',description:`<p>${name}</p>`,visibility:'published',publicationStatus:'published',parentId,data});check(x.status===201,`create ${resourceType}`,x.data);created.push(x.data.resource.id);return x.data.resource};
 const lore=await create('lore','E2E Lore',{summary:'Lore summary'}),artifact=await create('artifact','E2E Artifact',{rarity:'Mythic',relatedIds:[lore.id]}),map=await create('map','E2E Map',{imageUrl:'https://example.com/map.webp'}),pin=await create('pin','E2E Pin',{x:.25,y:.75,relatedIds:[lore.id,artifact.id]},map.id),timeline=await create('timeline','E2E Timeline',{calendarSystem:'Common Era'}),event=await create('timeline_event','E2E Event',{exactDate:'2026-07-18',relatedIds:[lore.id,artifact.id,pin.id]},timeline.id),power=await create('power_system','E2E Power',{summary:'Power summary',relatedIds:[artifact.id]}),node=await create('node','E2E Character',{x:100,y:100,relatedIds:[lore.id]}),relationship=await create('relationship','Owns',{sourceId:node.id,targetId:artifact.id,label:'Owns',direction:'directed',importance:2});
 r=await reader.call('GET',`/api/worldbuilding/${novelId}/resources`);check(r.ok&&r.data.mode==='published'&&created.every(id=>r.data.resources.some((x:any)=>x.id===id)),'reader views all published resources without premium',r.data);
 const firstVersion=Number((await db.query(`SELECT version FROM worldbuilding_cache_versions WHERE novel_id=$1`,[novelId])).rows[0].version),firstKey=publicWorldbuildingCacheKey(novelId,firstVersion,'all'),firstCached=await cache.get<any[]>(firstKey);check(Array.isArray(firstCached)&&firstCached.every(x=>x.publication_status==='published'&&x.visibility==='published'),'first public read populates published-only cache',firstCached);r=await reader.call('GET',`/api/worldbuilding/${novelId}/resources`);check(r.ok&&(await cache.get(firstKey))!==null,'second public read reuses cache');
 r=await reader.call('POST',`/api/worldbuilding/${novelId}/resources`,{resourceType:'lore',name:'Forbidden',visibility:'draft',publicationStatus:'draft',data:{}});check(r.status===403,'Premium Reader without Writer cannot mutate Worldbuilding');
 r=await premiumAction(readerId,'writer','grant',{durationSeconds:86400});check(r.ok,'grant unrelated user Writer Premium',r.data);r=await reader.call('POST',`/api/worldbuilding/${novelId}/resources`,{resourceType:'map',name:'Unrelated writer map must fail',visibility:'draft',publicationStatus:'draft',data:{}});check(r.status===403,'Premium Writer who is not owner or collaborator is denied');await db.query(`INSERT INTO novel_collaborators(novel_id,user_id,can_manage_worldbuilding) VALUES($1,$2,true) ON CONFLICT(novel_id,user_id) DO UPDATE SET can_manage_worldbuilding=true`,[novelId,readerId]);r=await reader.call('POST',`/api/worldbuilding/${novelId}/resources`,{resourceType:'map',name:'Authorized collaborator map',visibility:'draft',publicationStatus:'draft',data:{}});check(r.status===201,'authorized collaborator with Writer Premium can manage maps',r.data);created.push(r.data.resource.id);await db.query(`DELETE FROM novel_collaborators WHERE novel_id=$1 AND user_id=$2`,[novelId,readerId]);
 r=await premiumAction(authorId,'writer','revoke',{entitlementId:writerGrant.id});check(r.ok,'admin revokes Writer without Reader changes',r.data);r=await author.call('PATCH',`/api/worldbuilding/${novelId}/resources/${lore.id}`,{name:'Must fail'});check(r.status===403,'revoked Writer cannot mutate');
 r=await reader.call('GET',`/api/worldbuilding/${novelId}/resources/${lore.id}`);check(r.ok&&r.data.resource.id===lore.id,'published content remains after Writer revoke');
 r=await premiumAction(authorId,'writer','grant',{durationSeconds:86400});check(r.ok,'admin restores Writer Premium',r.data);r=await author.call('PATCH',`/api/worldbuilding/${novelId}/resources/${lore.id}`,{name:'E2E Lore Restored'});check(r.ok,'restored Writer can edit immediately',r.data);
 r=await author.call('PATCH',`/api/worldbuilding/${novelId}/resources/${lore.id}`,{publicationStatus:'draft',visibility:'draft'});check(r.ok,'unpublish invalidates public cache');const secondVersion=Number((await db.query(`SELECT version FROM worldbuilding_cache_versions WHERE novel_id=$1`,[novelId])).rows[0].version);check(secondVersion>firstVersion,'mutation increments durable cache version');r=await reader.call('GET',`/api/worldbuilding/${novelId}/resources`);check(r.ok&&Array.isArray(r.data.resources)&&!r.data.resources.some((x:any)=>x.id===lore.id),'draft content never enters new public cache',r.data);r=await author.call('PATCH',`/api/worldbuilding/${novelId}/resources/${lore.id}`,{publicationStatus:'published',visibility:'published'});check(r.ok,'republish refreshes public cache');
 r=await author.call('GET',`/api/worldbuilding/${novelId}/resources/${lore.id}/revisions`);check(r.ok&&r.data.revisions.length>0,'revision history created');
 r=await admin.call('GET',`/api/admin/users/${authorId}/premium`);check(r.ok&&r.data.audit.filter((x:any)=>x.premium_type==='writer').length>=3,'admin premium actions create immutable audit history',r.data.audit);
 r=await admin.call('DELETE',`/api/admin/users/${readerId}`);check(r.ok,'admin can delete a user with premium history',r.data);
 console.log('RESULT Worldbuilding end-to-end flow passed');
}finally{await db.query(`DELETE FROM novels WHERE id=$1`,[novelId]).catch(()=>{});await db.query(`DELETE FROM users WHERE username=ANY($1)`,[[authorName,readerName,adminName]]).catch(()=>{});await db.pool.end()}
