import {v4 as uuid} from "uuid";
import type {PoolClient} from "pg";
import {db} from "../postgres";
import {cache} from "./cache";
export type PremiumType="reader"|"writer";
export type PremiumActionName="grant"|"activate"|"deactivate"|"revoke"|"extend"|"shorten"|"renew"|"pause"|"resume"|"expire"|"set_dates"|"make_permanent"|"make_temporary";
export const PREMIUM_TYPES=new Set<PremiumType>(["reader","writer"]);
export const PREMIUM_SOURCES=new Set(["paid_subscription","admin_grant","promotion","trial","gift","migration","support_compensation","other"]);
const ACTIONS=new Set<PremiumActionName>(["grant","activate","deactivate","revoke","extend","shorten","renew","pause","resume","expire","set_dates","make_permanent","make_temporary"]);
const entitlementKey=(userId:string,version:number)=>`app:v1:user:${userId}:entitlements:v${version}`;
export function isEffective(row:any,now=new Date()){return row.status==="active"&&!row.is_paused&&!row.revoked_at&&new Date(row.starts_at).getTime()<=now.getTime()&&(row.is_permanent||(row.expires_at&&new Date(row.expires_at).getTime()>now.getTime()));}
export async function getEffectiveEntitlements(userId:string,skipCache=false){const load=async()=>{const{rows}=await db.query(`SELECT * FROM user_premium_entitlements WHERE user_id=$1 ORDER BY created_at`,[userId]);const active=rows.filter(row=>isEffective(row));return{reader:active.some(row=>row.premium_type==="reader"),writer:active.some(row=>row.premium_type==="writer"),sources:active,checkedAt:new Date().toISOString()}};if(skipCache)return load();const version=Number((await db.query(`INSERT INTO premium_entitlement_cache_versions(user_id) VALUES($1) ON CONFLICT(user_id) DO UPDATE SET user_id=EXCLUDED.user_id RETURNING version`,[userId])).rows[0].version);return cache.rememberAuthoritative(entitlementKey(userId,version),load,Number(process.env.PREMIUM_CACHE_TTL_SECONDS||60));}
export async function hasReaderPremium(userId:string){return(await getEffectiveEntitlements(userId)).reader}export async function hasWriterPremium(userId:string){return(await getEffectiveEntitlements(userId)).writer}export async function invalidateEntitlements(userId:string){await cache.del(`app:v1:user:${userId}:entitlements`)}
export async function getActiveWriterPremiumUserIds(userIds:string[],now=new Date()){
 const unique=[...new Set((userIds||[]).map(String).filter(Boolean))];if(!unique.length)return new Set<string>();
 const{rows}=await db.query(`SELECT DISTINCT user_id FROM user_premium_entitlements WHERE user_id=ANY($1::text[]) AND premium_type='writer' AND status='active' AND is_paused=false AND revoked_at IS NULL AND starts_at<=$2 AND (is_permanent=true OR expires_at>$2)`,[unique,now.toISOString()]);
 return new Set<string>(rows.map((row:any)=>String(row.user_id)));
}
export type PremiumAction={action:PremiumActionName;premiumType:PremiumType;entitlementId?:string;source?:string;startsAt?:string;expiresAt?:string|null;durationSeconds?:number;extensionMode?:"add"|"replace"|"from_now"|"after_existing";permanent?:boolean;autoRenew?:boolean;paymentSubscriptionId?:string;reason?:string;correlationId?:string};
function date(value:string|undefined,label:string){if(!value)return undefined;const result=new Date(value);if(!Number.isFinite(result.getTime()))throw new Error(`${label} is invalid`);return result;}
function validateAction(input:PremiumAction){if(!PREMIUM_TYPES.has(input.premiumType))throw new Error("Invalid premium type");if(!ACTIONS.has(input.action))throw new Error("Invalid premium action");if(input.source&&!PREMIUM_SOURCES.has(input.source))throw new Error("Invalid premium source");if(!String(input.reason||"").trim())throw new Error("Internal reason is required");const duration=Number(input.durationSeconds||0);if(duration<0||!Number.isFinite(duration))throw new Error("Duration must be a positive number");if(input.permanent&&input.expiresAt)throw new Error("Permanent access cannot have an expiration date");date(input.startsAt,"Start date");date(input.expiresAt||undefined,"Expiration date");}
async function applyWithClient(client:PoolClient,userId:string,adminId:string|null,input:PremiumAction){
 validateAction(input);let previous:any=null;if(input.entitlementId){previous=(await client.query(`SELECT * FROM user_premium_entitlements WHERE id=$1 AND user_id=$2 AND premium_type=$3 FOR UPDATE`,[input.entitlementId,userId,input.premiumType])).rows[0];if(!previous&&input.action!=="grant")throw new Error("Entitlement not found");}
 const now=new Date();let next:any=previous?{...previous}:null;if(!previous&&!['grant','activate'].includes(input.action))throw new Error("entitlementId is required");if(!previous)next={id:input.entitlementId||uuid(),user_id:userId,premium_type:input.premiumType,source:input.source||"admin_grant",status:"active",starts_at:input.startsAt||now.toISOString(),expires_at:null,is_permanent:false,is_paused:false,auto_renew:!!input.autoRenew,payment_subscription_id:input.paymentSubscriptionId||null,granted_by_admin_id:adminId,granted_at:now.toISOString()};
 const duration=Number(input.durationSeconds||0),start=date(input.startsAt,"Start date"),explicitExpiry=date(input.expiresAt||undefined,"Expiration date");if(start)next.starts_at=start.toISOString();
 if(input.action==="deactivate"){next.status="cancelled";next.revoked_at=now.toISOString();next.revoked_by_admin_id=adminId;}
 if(input.action==="revoke"){next.status="revoked";next.revoked_at=now.toISOString();next.revoked_by_admin_id=adminId;}
 if(input.action==="expire"){next.status="expired";next.is_permanent=false;next.expires_at=now.toISOString();}
 if(input.action==="pause"){if(!isEffective(next,now))throw new Error("Only active access can be paused");next.status="paused";next.is_paused=true;next.paused_at=now.toISOString();next.remaining_duration_at_pause=next.is_permanent?null:Math.max(0,Math.floor((new Date(next.expires_at).getTime()-now.getTime())/1000));}
 if(input.action==="resume"){if(!next.is_paused&&next.status!=="paused")throw new Error("Entitlement is not paused");next.status="active";next.is_paused=false;if(!next.is_permanent&&next.remaining_duration_at_pause!=null)next.expires_at=new Date(now.getTime()+Number(next.remaining_duration_at_pause)*1000).toISOString();next.paused_at=null;next.remaining_duration_at_pause=null;}
 if(input.permanent||input.action==="make_permanent"){next.is_permanent=true;next.expires_at=null;}
 if(input.action==="make_temporary"){if(!explicitExpiry&&!duration)throw new Error("Temporary access requires an expiration or duration");next.is_permanent=false;}
 if(explicitExpiry&&!next.is_permanent)next.expires_at=explicitExpiry.toISOString();
 if(duration&&!next.is_permanent){const current=next.expires_at?new Date(next.expires_at):now;let base=!previous&&start?start:now;if(input.extensionMode==="add"||input.extensionMode==="after_existing")base=current>now?current:base;if(input.extensionMode==="replace"&&start)base=start;next.expires_at=new Date(base.getTime()+duration*1000).toISOString();}
 if(["grant","activate","renew"].includes(input.action)){next.status=new Date(next.starts_at)>now?"scheduled":"active";next.revoked_at=null;next.revoked_by_admin_id=null;next.is_paused=false;}
 if(!next.is_permanent&&!next.expires_at)throw new Error("Temporary access requires an expiration date");if(!next.is_permanent&&new Date(next.expires_at)<=new Date(next.starts_at)&&!['expire','revoke','deactivate'].includes(input.action))throw new Error("Expiration must be after the start date");if(previous?.is_permanent&&["extend","renew"].includes(input.action)&&!input.permanent&&!explicitExpiry&&!duration){next.is_permanent=true;next.expires_at=null;}
 next.updated_at=now.toISOString();next.internal_note=String(input.reason).trim();const columns=["id","user_id","premium_type","status","source","starts_at","expires_at","is_permanent","is_paused","paused_at","remaining_duration_at_pause","auto_renew","payment_subscription_id","granted_by_admin_id","revoked_by_admin_id","granted_at","revoked_at","internal_note","updated_at"];const values=columns.map(k=>next[k]??null),params=values.map((_,i)=>`$${i+1}`).join(","),updates=columns.slice(1).map(k=>`${k}=EXCLUDED.${k}`).join(",");const saved=(await client.query(`INSERT INTO user_premium_entitlements(${columns.join(",")}) VALUES(${params}) ON CONFLICT(id) DO UPDATE SET ${updates} RETURNING *`,values)).rows[0];const previousExpiry=previous?.expires_at?new Date(previous.expires_at).getTime():null,newExpiry=saved.expires_at?new Date(saved.expires_at).getTime():null,delta=previousExpiry!==null&&newExpiry!==null?Math.round((newExpiry-previousExpiry)/1000):duration||null;await client.query(`INSERT INTO premium_entitlement_audit(id,user_id,entitlement_id,premium_type,previous_state,new_state,action_type,duration_delta_seconds,previous_expires_at,new_expires_at,performing_admin_id,internal_reason,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[uuid(),userId,saved.id,input.premiumType,previous?JSON.stringify(previous):null,JSON.stringify(saved),input.action,delta,previous?.expires_at||null,saved.expires_at,adminId,input.reason,input.correlationId||uuid()]);await client.query(`INSERT INTO premium_entitlement_cache_versions(user_id,version) VALUES($1,2) ON CONFLICT(user_id) DO UPDATE SET version=premium_entitlement_cache_versions.version+1,updated_at=now()`,[userId]);return saved;
}
export async function applyPremiumAction(userId:string,adminId:string|null,input:PremiumAction){const result=await db.withTransaction(client=>applyWithClient(client,userId,adminId,input));await invalidateEntitlements(userId);return result;}
export async function applyPremiumActions(userId:string,adminId:string|null,inputs:PremiumAction[]){const correlationId=inputs[0]?.correlationId||uuid();const results=await db.withTransaction(async client=>{const rows=[];for(const input of inputs)rows.push(await applyWithClient(client,userId,adminId,{...input,correlationId}));return rows});await invalidateEntitlements(userId);return results;}
