import express from "express";
import sanitizeHtml from "sanitize-html";
import {v4 as uuid} from "uuid";
import {db} from "../../postgres";
import {getActiveUser,isOwnerUser} from "../../utils/auth";
import {hasWriterPremium} from "../../utils/premiumEntitlements";
import {cache} from "../../utils/cache";
import {WORLD_TYPES,previewWorldbuildingCacheKey,publicWorldbuildingCacheKey,referencedIds,ttlWithJitter,validateWorldbuildingInput} from "../../utils/worldbuilding";

const router=express.Router();
function sanitizeRichText(value:any){return sanitizeHtml(String(value||''),{allowedTags:['p','br','strong','em','s','blockquote','ul','ol','li','h1','h2','h3','hr','a','img'],allowedAttributes:{a:['href','target','rel'],img:['src','alt','title','width','height']},allowedSchemes:['http','https','mailto'],transformTags:{a:sanitizeHtml.simpleTransform('a',{rel:'noopener noreferrer'})}}).slice(0,100000)}
async function context(req:any){const user=await getActiveUser(req,['POST','PUT','PATCH','DELETE'].includes(req.method));const novel=(await db.query(`SELECT id,author_id,approval_status FROM novels WHERE id=$1`,[req.params.novelId])).rows[0];return{user,novel};}
async function collaborator(userId:string,novelId:string){return (await db.query(`SELECT can_manage_worldbuilding FROM novel_collaborators WHERE user_id=$1 AND novel_id=$2`,[userId,novelId])).rows[0];}
async function canPreview(user:any,novel:any){return !!user&&!!novel&&(isOwnerUser(user)||user.id===novel.author_id||!!await collaborator(user.id,novel.id));}
async function canManage(user:any,novel:any){if(!user||!novel)return false;if(isOwnerUser(user))return true;const membership=user.id===novel.author_id?{can_manage_worldbuilding:true}:await collaborator(user.id,novel.id);return !!membership?.can_manage_worldbuilding&&await hasWriterPremium(user.id);}
async function version(novelId:string){const row=(await db.query(`INSERT INTO worldbuilding_cache_versions(novel_id) VALUES($1) ON CONFLICT(novel_id) DO UPDATE SET novel_id=EXCLUDED.novel_id RETURNING version`,[novelId])).rows[0],value=Number(row.version);void cache.set(`app:v1:worldbuilding:novel:${novelId}:version`,value,86400);return value;}
async function bumpVersion(client:any,novelId:string){const row=(await client.query(`INSERT INTO worldbuilding_cache_versions(novel_id,version) VALUES($1,2) ON CONFLICT(novel_id) DO UPDATE SET version=worldbuilding_cache_versions.version+1,updated_at=now() RETURNING version`,[novelId])).rows[0];return Number(row.version);}
async function publishVersion(novelId:string,nextVersion:number){try{await cache.set(`app:v1:worldbuilding:novel:${novelId}:version`,nextVersion,86400);}catch(error){console.error('worldbuilding cache invalidation failed',{novelId,error});}}
function publicResource(row:any,allowedIds?:Set<string>){const{created_by,updated_by,...safe}=row;const data:any=Object.fromEntries(Object.entries(safe.data||{}).filter(([key])=>!/^(_|internal|admin)/i.test(key)));if(allowedIds&&Array.isArray(data.relatedIds))data.relatedIds=data.relatedIds.filter((id:string)=>allowedIds.has(id));for(const key of ['sourceId','targetId','linkedResourceId','relatedLocationId'])if(data[key]&&!allowedIds?.has(data[key]))delete data[key];return{...safe,data};}
function sendError(res:any,e:any){const status=e.status||(e.code==='23505'?409:400);const message=e.code==='23505'?'یک رابطه یا منبع تکراری از قبل وجود دارد':(e.status?e.message:'انجام این درخواست ممکن نبود');return res.status(status).json({error:message,code:e.code==='23505'?'DUPLICATE_RESOURCE':'REQUEST_FAILED'});}
// Resource names/subtypes are plain text; resource data is JSONB whose only
// URL-bearing fields (anything ending in url/Url/imageUrl) must be http(s).
function safeName(value:any){return sanitizeHtml(String(value??''),{allowedTags:[],allowedAttributes:{}}).trim().slice(0,200)}
// ✅ SECURITY: Whitelist of allowed top-level data keys per resource type.
// Without this, an attacker could store arbitrary nested objects containing
// XSS payloads that get rendered unescaped in the frontend.
const ALLOWED_WORLDBUILDING_DATA_KEYS = new Set([
  "name", "description", "subtype", "color", "icon", "imageUrl", "coverUrl",
  "sourceId", "targetId", "linkedResourceId", "relatedLocationId",
  "relatedIds", "relationshipType", "directed", "biography", "role",
  "age", "occupation", "aliases", "tags", "metadata",
  "position", "size", "shape", "coordinates", "startDate", "endDate",
]);

// ✅ SECURITY: Recursively sanitize HTML from string values. Even though
// we restrict top-level keys, nested objects can still contain XSS payloads.
function sanitizeStringValue(value: any): any {
  if (typeof value === "string") {
    // Strip HTML tags from strings stored in JSONB. The frontend can
    // re-render them as text safely.
    return value
      .replace(/<\s*(script|iframe|object|embed|style|link|meta|base|form)\b[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, "")
      .replace(/<[^>]+>/g, "")
      .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "")
      .slice(0, 10000);
  }
  if (Array.isArray(value)) return value.slice(0, 100).map(sanitizeStringValue);
  if (value && typeof value === "object") {
    const clean: any = {};
    for (const [k, v] of Object.entries(value)) {
      if (/^(_|internal|admin)/i.test(k)) continue;
      clean[k] = sanitizeStringValue(v);
    }
    return clean;
  }
  return value;
}

function sanitizeResourceData(data:any){
  if(!data||typeof data!=='object'||Array.isArray(data))return{};
  const clean:any={};
  for(const key of Object.keys(data)){
    // ✅ SECURITY: Only allow whitelisted keys.
    if(!ALLOWED_WORLDBUILDING_DATA_KEYS.has(key))continue;
    if(/^(_|internal|admin)/i.test(key))continue;
    if(/url$/i.test(key)&&data[key]!=null&&data[key]!==''){
      const v=String(data[key]).trim();
      clean[key]=/^https?:\/\//i.test(v)?v.slice(0,2048):'';
    }else{
      // ✅ SECURITY: Recursively sanitize nested values.
      clean[key]=sanitizeStringValue(data[key]);
    }
  }
  if(Array.isArray(clean.relatedIds))clean.relatedIds=clean.relatedIds.map((x:any)=>String(x).slice(0,120)).filter((x:string)=>/^[a-zA-Z0-9_-]+$/.test(x)).slice(0,50);
  return clean;
}
async function validateReferences(novelId:string,input:any){const ids=referencedIds(input);if(input.parentId)ids.push(input.parentId);if(!ids.length)return{};const rows=(await db.query(`SELECT id,resource_type,parent_id FROM worldbuilding_resources WHERE novel_id=$1 AND id=ANY($2)`,[novelId,[...new Set(ids)]])).rows,found=new Map(rows.map((x:any)=>[x.id,x]));const missing=ids.filter(id=>!found.has(id));if(missing.length)return{references:`شناسه‌های منبع نامعلوم یا متعلق به رمان دیگری هستند: ${missing.join(', ')}`};if(input.parentId){const expected:any={map:'map',pin:'map',timeline_event:'timeline'};if(expected[input.resourceType]&&found.get(input.parentId)?.resource_type!==expected[input.resourceType])return{parentId:`منبع والد باید از نوع ${expected[input.resourceType]} باشد`};if(input.parentId===input.id)return{parentId:'یک منبع نمی‌تواند والد خودش باشد'};}return{}}
async function validateRelationshipDuplicate(novelId:string,input:any,excludeId?:string){if(input.resourceType!=='relationship'||!input.data?.sourceId||!input.data?.targetId)return{};const d=input.data;const params:any[]=[novelId,d.sourceId,d.targetId,String(d.relationshipType||input.subtype||'related'),!!d.directed];let sql=`SELECT id FROM worldbuilding_resources WHERE novel_id=$1 AND resource_type='relationship' AND COALESCE(data->>'relationshipType',subtype,'related')=$4 AND ((data->>'sourceId'=$2 AND data->>'targetId'=$3) OR ($5=false AND data->>'sourceId'=$3 AND data->>'targetId'=$2))`;if(excludeId){params.push(excludeId);sql+=` AND id<>$6`;}return(await db.query(sql,params)).rowCount?{relationship:'این رابطه از قبل وجود دارد'}:{};}

router.get('/:novelId/resources',async(req,res)=>{try{const{user,novel}=await context(req);if(!novel)return res.status(404).json({error:'رمان یافت نشد'});const privileged=await canPreview(user,novel);if(!privileged&&novel.approval_status!=='approved')return res.status(404).json({error:'رمان یافت نشد'});const type=String(req.query.type||'');if(type&&!WORLD_TYPES.has(type))return res.status(422).json({error:'اعتبارسنجی ناموفق بود',fields:{type:'نوع منبع پشتیبانی نمی‌شود'}});const v=Number(await version(novel.id));const key=privileged?previewWorldbuildingCacheKey(novel.id,v,user.id,type||'all'):publicWorldbuildingCacheKey(novel.id,v,type||'all');const rows=await cache.remember(key,async()=>{const params:any[]=[novel.id];let sql=`SELECT * FROM worldbuilding_resources WHERE novel_id=$1`;if(type){params.push(type);sql+=` AND resource_type=$2`;}if(!privileged)sql+=` AND visibility='published' AND publication_status='published'`;const result=(await db.query(`${sql} ORDER BY display_order,created_at`,params)).rows;if(privileged)return result;const allowedIds=new Set((await db.query(`SELECT id FROM worldbuilding_resources WHERE novel_id=$1 AND publication_status='published' AND visibility='published'`,[novel.id])).rows.map((row:any)=>row.id));return result.filter((row:any)=>row.resource_type!=='relationship'||(allowedIds.has(row.data?.sourceId)&&allowedIds.has(row.data?.targetId))).map((row:any)=>publicResource(row,allowedIds));},ttlWithJitter(Number(process.env.WORLDBUILDING_CACHE_TTL_SECONDS||600)));res.setHeader('X-Worldbuilding-Cache-Key',key);res.json({resources:rows,mode:privileged?'preview':'published',permissions:{canPreview:privileged,canManage:await canManage(user,novel),canManageMaps:await canManage(user,novel)}});}catch(e:any){sendError(res,e);}});
router.get('/:novelId/resources/:id',async(req,res)=>{try{const{user,novel}=await context(req);const row=(await db.query(`SELECT * FROM worldbuilding_resources WHERE id=$1 AND novel_id=$2`,[req.params.id,req.params.novelId])).rows[0];if(!row)return res.status(404).json({error:'منبع یافت نشد'});const privileged=await canPreview(user,novel);if(!privileged&&!(novel?.approval_status==='approved'&&row.publication_status==='published'&&(row.visibility==='published'||row.visibility==='unlisted')))return res.status(404).json({error:'منبع یافت نشد'});if(privileged)return res.json({resource:row});const allowed=new Set((await db.query(`SELECT id FROM worldbuilding_resources WHERE novel_id=$1 AND publication_status='published' AND visibility IN ('published','unlisted')`,[req.params.novelId])).rows.map((x:any)=>x.id));if(row.resource_type==='relationship'&&(!allowed.has(row.data?.sourceId)||!allowed.has(row.data?.targetId)))return res.status(404).json({error:'منبع یافت نشد'});res.json({resource:publicResource(row,allowed)});}catch(e:any){sendError(res,e);}});
router.get('/:novelId/resources/:id/revisions',async(req,res)=>{try{const{user,novel}=await context(req);if(!await canPreview(user,novel))return res.status(403).json({error:'دسترسی غیرمجاز'});const rows=(await db.query(`SELECT id,revision,snapshot,created_by,created_at FROM worldbuilding_revisions WHERE novel_id=$1 AND resource_id=$2 ORDER BY revision DESC LIMIT 100`,[req.params.novelId,req.params.id])).rows;res.json({revisions:rows});}catch(e:any){res.status(400).json({error:e.message});}});
router.post('/:novelId/resources/reorder',async(req,res)=>{try{const{user,novel}=await context(req);const ids=Array.isArray(req.body.ids)?req.body.ids.map(String):[];if(!ids.length||new Set(ids).size!==ids.length||ids.length>1000)return res.status(422).json({error:'اعتبارسنجی ناموفق بود',fields:{ids:'بین 1 تا 1000 شناسه منبع یکتا ارائه دهید'}});const allowed=await canManage(user,novel);if(!allowed)return res.status(403).json({error:'این عملیات به اشتراک فعال نویسنده پریمیوم و مالکیت یا همکاری در رمان نیاز دارد'});const result=await db.withTransaction(async client=>{const locked=(await client.query(`SELECT id,parent_id,resource_type FROM worldbuilding_resources WHERE novel_id=$1 AND id=ANY($2) FOR UPDATE`,[novel.id,ids])).rows;if(locked.length!==ids.length)throw Object.assign(new Error('یک یا چند منبع متعلق به این رمان نیستند'),{status:422});const signature=new Set(locked.map((x:any)=>`${x.resource_type}:${x.parent_id||''}`));if(signature.size!==1)throw Object.assign(new Error('همه منابع باید نوع و والد یکسانی داشته باشند'),{status:422});await Promise.all(ids.map((id:string,index:number)=>client.query(`UPDATE worldbuilding_resources SET display_order=$1,updated_by=$2,updated_at=now(),version=version+1 WHERE id=$3 AND novel_id=$4`,[index,user.id,id,novel.id])));return{nextVersion:await bumpVersion(client,novel.id)}});await publishVersion(novel.id,result.nextVersion);res.json({success:true});}catch(e:any){sendError(res,e);}});
router.post('/:novelId/resources',async(req,res)=>{try{const{user,novel}=await context(req);const allowed=await canManage(user,novel);if(!allowed)return res.status(403).json({error:'این عملیات به اشتراک فعال نویسنده پریمیوم و مالکیت یا همکاری در رمان نیاز دارد'});const errors={...validateWorldbuildingInput(req.body),...await validateReferences(novel.id,req.body),...await validateRelationshipDuplicate(novel.id,req.body)};if(Object.keys(errors).length)return res.status(422).json({error:'اعتبارسنجی ناموفق بود',fields:errors});const visibility=req.body.visibility||'draft',publication=req.body.publicationStatus||'draft';const result=await db.withTransaction(async client=>{const row=(await client.query(`INSERT INTO worldbuilding_resources(id,novel_id,resource_type,parent_id,name,subtype,description,visibility,publication_status,display_order,data,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING *`,[uuid(),novel.id,req.body.resourceType,req.body.parentId||null,safeName(req.body.name),req.body.subtype?safeName(req.body.subtype):null,req.body.description?sanitizeRichText(req.body.description):null,visibility,publication,Number(req.body.displayOrder||0),sanitizeResourceData(req.body.data),user.id])).rows[0];return{row,nextVersion:await bumpVersion(client,novel.id)}});await publishVersion(novel.id,result.nextVersion);res.status(201).json({resource:result.row});}catch(e:any){sendError(res,e);}});
router.patch('/:novelId/resources/:id',async(req,res)=>{try{const{user,novel}=await context(req);const current=(await db.query(`SELECT resource_type FROM worldbuilding_resources WHERE id=$1 AND novel_id=$2`,[req.params.id,novel.id])).rows[0];if(!current)return res.status(404).json({error:'منبع یافت نشد'});const permitted=await canManage(user,novel);if(!permitted)return res.status(403).json({error:'این عملیات به اشتراک فعال نویسنده پریمیوم و مالکیت یا همکاری در رمان نیاز دارد'});const normalized={...req.body,id:req.params.id,resourceType:current.resource_type};const validation={...validateWorldbuildingInput(normalized,true),...await validateReferences(novel.id,normalized),...await validateRelationshipDuplicate(novel.id,normalized,req.params.id)};if(Object.keys(validation).length)return res.status(422).json({error:'اعتبارسنجی ناموفق بود',fields:validation});const allowed:any={name:req.body.name===undefined?undefined:safeName(req.body.name),subtype:req.body.subtype===undefined?undefined:safeName(req.body.subtype),description:req.body.description===undefined?undefined:sanitizeRichText(req.body.description),visibility:req.body.visibility,publication_status:req.body.publicationStatus,display_order:req.body.displayOrder,parent_id:req.body.parentId,data:req.body.data===undefined?undefined:sanitizeResourceData(req.body.data)};const entries=Object.entries(allowed).filter(([,v])=>v!==undefined);if(!entries.length)return res.status(400).json({error:'تغییری برای اعمال وجود ندارد'});const result=await db.withTransaction(async client=>{const old=(await client.query(`SELECT * FROM worldbuilding_resources WHERE id=$1 AND novel_id=$2 FOR UPDATE`,[req.params.id,novel.id])).rows[0];if(!old)throw Object.assign(new Error('Not found'),{status:404});if(req.body.expectedVersion!==undefined&&Number(req.body.expectedVersion)!==Number(old.version))throw Object.assign(new Error('این منبع در نشست دیگری تغییر کرده است. پیش از ذخیره، صفحه را دوباره بارگذاری کنید.'),{status:409});await client.query(`INSERT INTO worldbuilding_revisions(id,novel_id,resource_id,revision,snapshot,created_by) SELECT $1,$2,$3,COALESCE(MAX(revision),0)+1,$4,$5 FROM worldbuilding_revisions WHERE resource_id=$3`,[uuid(),novel.id,old.id,old,user.id]);const vals=entries.map(([,v])=>v);vals.push(user.id,old.id,novel.id);const sets=entries.map(([k],i)=>`${k}=$${i+1}`).join(',');const row=(await client.query(`UPDATE worldbuilding_resources SET ${sets},updated_by=$${entries.length+1},updated_at=now(),version=version+1 WHERE id=$${entries.length+2} AND novel_id=$${entries.length+3} RETURNING *`,vals)).rows[0];return{row,nextVersion:await bumpVersion(client,novel.id)}});await publishVersion(novel.id,result.nextVersion);res.json({resource:result.row});}catch(e:any){sendError(res,e);}});
router.delete('/:novelId/resources/:id',async(req,res)=>{try{const{user,novel}=await context(req);const target=(await db.query(`SELECT resource_type FROM worldbuilding_resources WHERE id=$1 AND novel_id=$2`,[req.params.id,novel.id])).rows[0];if(!target)return res.status(404).json({error:'منبع یافت نشد'});const allowed=await canManage(user,novel);if(!allowed)return res.status(403).json({error:'این عملیات به اشتراک فعال نویسنده پریمیوم و مالکیت یا همکاری در رمان نیاز دارد'});const result=await db.withTransaction(async client=>{const deleted=await client.query(`DELETE FROM worldbuilding_resources WHERE id=$1 AND novel_id=$2 RETURNING id`,[req.params.id,novel.id]);return{deleted,nextVersion:deleted.rowCount?await bumpVersion(client,novel.id):null}});if(!result.deleted.rowCount)return res.status(404).json({error:'منبع یافت نشد'});await publishVersion(novel.id,result.nextVersion!);res.json({success:true});}catch(e:any){sendError(res,e);}});
export default router;
